---
title: Time series in Tidy framework
author: Emrick Liu
date: '2019-03-28'
slug: time-series-in-tidy-framework
categories:
  - R
tags:
  - tsibble
  - tidyverse
  - tidyquant
keywords:
  - tech
---
# Overview

Tidyverse has been around for quite a while, however, it make one common date type unwieldy: matix. Unfortunately, matrix is what many popular times series functionalities packages based on, such as famous `xts` package. Most promising packages that handle time series in my eyes are `tsibble` and `tidyquant`. By no means, there is "use one or the other" relationship between these two packages. Base on the names alone, one can aware of that they have very different goals in minds. `tsibble` is aiming to come up with general purpose packages that can handle time series while `tidyquant` has more domain focus on finance, namely, portfolio management.

In this post, I would like to explore these 2 packages w.r.t their overlapped functionalities in order to have a better idea which one would be a better choice for the job.



